remote_trigger:
  name: Remote Trigger
  description: Remotely trigger the Assist satellite.
  fields:
    entity_id:
      name: Entity ID
      description: The satellite entity to trigger.
      required: true
      example: assist_satellite.hassmic_wyoming
      selector:
        entity:
          domain: assist_satellite
